project:
  type: website
  output-dir: docs


website:
  title: "Emmanuel Laureano Maravilla Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href:  college-cost-analysis.qmd
        text: "College Cost Analysis"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: source

